"""Build data/exoplanets.js from NASA Exoplanet Archive confirmed systems.

Usage:
    python tools/build_exoplanets.py

Output: data/exoplanets.js defining window.EXOPLANET_HOSTS = { meta, hosts }.
Hosts are grouped from the NASA Exoplanet Archive PSCompPars TAP table, with
one rendered entry per host star.
"""
from __future__ import annotations

import argparse
import json
import sys
import urllib.parse
import urllib.request
from collections import defaultdict
from pathlib import Path


TAP_URL = "https://exoplanetarchive.ipac.caltech.edu/TAP/sync"
LY_PER_PC = 3.26156


def compact_float(value: float | None, places: int) -> float | None:
    if value is None:
        return None
    rounded = round(float(value), places)
    return int(rounded) if rounded.is_integer() else rounded


def fetch_json(query: str) -> list[dict]:
    url = TAP_URL + "?" + urllib.parse.urlencode({"query": query, "format": "json"})
    req = urllib.request.Request(url, headers={"User-Agent": "MessierAtlas/1.0"})
    with urllib.request.urlopen(req, timeout=180) as resp:
        return json.loads(resp.read().decode("utf-8"))


def build_hosts(rows: list[dict]) -> list[list]:
    grouped: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        host = (row.get("hostname") or "").strip()
        if host:
            grouped[host].append(row)

    hosts = []
    for host, items in grouped.items():
        planets = sorted({(item.get("pl_name") or "").strip() for item in items if item.get("pl_name")})
        if not planets:
            continue

        # System parameters should be the same per host in pscomppars, but use
        # medians-by-position would be overkill here; the first complete row is
        # enough for a display layer.
        source = next(
            item for item in items
            if item.get("ra") is not None and item.get("dec") is not None and item.get("sy_dist") is not None
        )
        methods = sorted({(item.get("discoverymethod") or "").strip() for item in items if item.get("discoverymethod")})
        years = sorted(int(item["disc_year"]) for item in items if item.get("disc_year") is not None)

        hosts.append([
            host,
            compact_float(source["ra"], 4),
            compact_float(source["dec"], 4),
            compact_float(float(source["sy_dist"]) * LY_PER_PC, 2),
            compact_float(source.get("sy_vmag"), 2),
            len(planets),
            planets[:8],
            methods[:5],
            years[0] if years else None,
            years[-1] if years else None,
        ])

    hosts.sort(key=lambda row: (-row[5], row[0].lower()))
    return hosts


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()

    query = """
        select hostname, pl_name, ra, dec, sy_dist, sy_vmag, discoverymethod, disc_year
        from pscomppars
        where hostname is not null
          and pl_name is not null
          and ra is not null
          and dec is not null
          and sy_dist is not null
    """
    rows = fetch_json(" ".join(query.split()))
    hosts = build_hosts(rows)

    payload = {
        "meta": {
            "source": "NASA Exoplanet Archive PSCompPars table",
            "source_url": "https://exoplanetarchive.ipac.caltech.edu/docs/API_PS_columns.html",
            "tap_url": TAP_URL,
            "columns": [
                "hostname", "ra", "dec", "dist_ly", "vmag", "planet_count",
                "planet_names", "discovery_methods", "first_disc_year", "last_disc_year",
            ],
            "planet_rows": len(rows),
            "host_count": len(hosts),
        },
        "hosts": hosts,
    }

    out = Path(__file__).resolve().parent.parent / "data" / "exoplanets.js"
    text = json.dumps(payload, ensure_ascii=True, separators=(",", ":"))
    out.write_text(
        "// Generated by tools/build_exoplanets.py from NASA Exoplanet Archive PSCompPars\n"
        "// hosts: confirmed exoplanet host stars grouped from planet rows\n"
        f"window.EXOPLANET_HOSTS={text};\n",
        encoding="ascii",
    )
    print(f"wrote {out}")
    print(f"planet rows: {len(rows):,}")
    print(f"host stars: {len(hosts):,}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(130)
